Update for Moodle 4.5
learnweb/moodle-mod_moodleoverflow pull request #199
Opened 2024-11-21 02:30 UTC by justusdieckmann

2025-03-06 13:37 UTC, dlmsr requested changes
The files in `amd/build` should be considered binary files. These are generated from the respective source files in `amd/src` and should only ever change together with the respective source files. Furthermore, these files target a certain Browser subset and therefore do not necessarily use the newest and recommended JS language features. This needs to be fixed.

2025-03-06 14:34 UTC, justusdieckmann commented
@dlmsr Just a quick note: Sometimes, there are changes to grunt, which cause it to output different transpiled code for the same javascript files than before.

In that case (which happened here), it does make sense to commit the changed binary files, because otherwise the grunt ci keeps complaining about the minified js files being wrong :)

2025-03-06 17:30 UTC, dlmsr commented
Am 6. März 2025 15:34:39 MEZ schrieb Justus Dieckmann ***@***.***>:
>justusdieckmann left a comment (learnweb/moodle-mod_moodleoverflow#199)
>
>@dlmsr Just a quick note: Sometimes, there are changes to grunt, which cause it to output different transpiled code for the same javascript files than before.

Fair point, I indeed overlooked this case.

>In that case (which happened here), it does make sense to commit the changed binary files, because otherwise the grunt ci keeps complaining about the minified js files being wrong :)

True! However, this is another reason not to commit generated files in the first place 🤐

2025-03-07 03:14 UTC, bluetom approved these changes

2025-03-07 03:24 UTC, bluetom commented
I get the point but I am afraid it is usual in the moodle plugin world to publish the minified files. Here some reasons:

> Potential Issues When Excluding Minified Files:
>
> - Deployment for End Users
> 
> If users download your plugin from GitHub instead of the Moodle Plugin Directory, they might expect ready-to-use files and may not have the tools to minify the JS themselves.
>
> - Moodle Plugin Directory Submission
> 
> When submitting a plugin to the Moodle Plugin Directory, it should include all necessary files (including minified JS) so that Moodle sites can use it without additional setup.
>
> - Continuous Deployment & CI/CD
> 
> If you rely on automated deployments from GitHub (e.g., direct installation on a production site from GitHub), missing minified files could break functionality.

2025-03-08 01:00 UTC, merged